"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-03-22 16:02:15.892011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "condition_id",
            sa.String(length=128),
            nullable=False,
            comment="Polymarket condition ID (market identifier)",
        ),
        sa.Column(
            "question",
            sa.Text(),
            nullable=False,
            comment="Human-readable market question",
        ),
        sa.Column("best_bid", sa.Float(), nullable=False),
        sa.Column("best_ask", sa.Float(), nullable=False),
        sa.Column("last_trade_price", sa.Float(), nullable=True),
        sa.Column("midpoint", sa.Float(), nullable=False),
        sa.Column("bid_liquidity_usdc", sa.Float(), nullable=False),
        sa.Column("ask_liquidity_usdc", sa.Float(), nullable=False),
        sa.Column(
            "outcome_token",
            sa.String(length=64),
            nullable=False,
            comment="YES or NO token address being tracked",
        ),
        sa.Column("market_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("volume_24h_usdc", sa.Float(), nullable=True),
        sa.Column(
            "raw_ws_payload",
            sa.Text(),
            nullable=False,
            comment="Original JSON string received from CLOB WebSocket",
        ),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_snapshots_captured_at"),
        "market_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_market_snapshots_condition_captured",
        "market_snapshots",
        ["condition_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_snapshots_condition_id"),
        "market_snapshots",
        ["condition_id"],
        unique=False,
    )
    op.create_table(
        "agent_decision_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column(
            "confidence_score",
            sa.Float(),
            nullable=False,
            comment="LLM confidence [0.0 – 1.0] in its probability estimate",
        ),
        sa.Column(
            "expected_value",
            sa.Float(),
            nullable=False,
            comment="Computed EV of the trade in USDC-equivalent basis",
        ),
        sa.Column(
            "decision_boolean",
            sa.Boolean(),
            nullable=False,
            comment="True = execute trade; False = hold",
        ),
        sa.Column(
            "recommended_action",
            sa.Enum("BUY", "SELL", "HOLD", name="decision_action_enum"),
            nullable=False,
        ),
        sa.Column(
            "implied_probability",
            sa.Float(),
            nullable=False,
            comment="LLM's estimated true probability for the outcome",
        ),
        sa.Column(
            "reasoning_log",
            sa.Text(),
            nullable=False,
            comment="Raw Chain-of-Thought text block returned verbatim by Claude",
        ),
        sa.Column(
            "prompt_version",
            sa.String(length=32),
            nullable=False,
            comment="Slug identifying the CoT prompt template version used",
        ),
        sa.Column(
            "llm_model_id",
            sa.String(length=64),
            nullable=False,
            comment="Exact model string returned by Anthropic API, e.g. claude-3-5-sonnet-20241022",
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["market_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_decision_logs_evaluated_at"),
        "agent_decision_logs",
        ["evaluated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_decision_logs_snapshot_id"),
        "agent_decision_logs",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "execution_txs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision_id", sa.String(length=36), nullable=False),
        sa.Column(
            "tx_hash",
            sa.String(length=66),
            nullable=True,
            comment="0x-prefixed Polygon transaction hash",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CONFIRMED", "FAILED", "REVERTED", name="tx_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("side", sa.String(length=4), nullable=False, comment="BUY or SELL"),
        sa.Column(
            "size_usdc",
            sa.Float(),
            nullable=False,
            comment="USDC amount committed to this order",
        ),
        sa.Column(
            "limit_price",
            sa.Float(),
            nullable=False,
            comment="Limit price submitted to the CLOB",
        ),
        sa.Column("condition_id", sa.String(length=128), nullable=False),
        sa.Column("outcome_token", sa.String(length=64), nullable=False),
        sa.Column("gas_limit", sa.Integer(), nullable=True),
        sa.Column("gas_price_gwei", sa.Float(), nullable=True),
        sa.Column("gas_used", sa.Integer(), nullable=True),
        sa.Column("nonce", sa.Integer(), nullable=True),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Revert reason or RPC error string if tx failed",
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["agent_decision_logs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tx_hash"),
    )
    op.create_index(
        op.f("ix_execution_txs_condition_id"),
        "execution_txs",
        ["condition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_txs_decision_id"),
        "execution_txs",
        ["decision_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_execution_txs_status"), "execution_txs", ["status"], unique=False
    )
    op.create_index(
        "ix_execution_txs_status_submitted",
        "execution_txs",
        ["status", "submitted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_execution_txs_status_submitted", table_name="execution_txs")
    op.drop_index(op.f("ix_execution_txs_status"), table_name="execution_txs")
    op.drop_index(op.f("ix_execution_txs_decision_id"), table_name="execution_txs")
    op.drop_index(op.f("ix_execution_txs_condition_id"), table_name="execution_txs")
    op.drop_table("execution_txs")
    op.drop_index(
        op.f("ix_agent_decision_logs_snapshot_id"), table_name="agent_decision_logs"
    )
    op.drop_index(
        op.f("ix_agent_decision_logs_evaluated_at"), table_name="agent_decision_logs"
    )
    op.drop_table("agent_decision_logs")
    op.drop_index(
        op.f("ix_market_snapshots_condition_id"), table_name="market_snapshots"
    )
    op.drop_index(
        "ix_market_snapshots_condition_captured", table_name="market_snapshots"
    )
    op.drop_index(
        op.f("ix_market_snapshots_captured_at"), table_name="market_snapshots"
    )
    op.drop_table("market_snapshots")
    # ### end Alembic commands ###
